name: 360

on:
  schedule:
    - cron: '0 5,11,17,23 * * *' # 每6小时触发一次

  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run iptv
        run: python ${{ github.workspace }}/tvs.py

        
      - name: 提交
        run: |
          git config --local user.email "115099300@qq.com"
          git config --local user.name "pany"
          git add .
          git commit *.txt -m "Add generated file"
          #git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
